### ISSUE TITLE
Add usage example in README file

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#1]
Remove the existing documentation in README below this heading
`Small package which provides some basic functions for custom date formatting`

and add usage examples something like this

https://github.com/arshadkazmi42/simple-date-validator/blob/master/README.md#how-to-use

**Comment by msarfrazanwar** [comment]
I will take this.

**Comment by arshadkazmi42** [comment]
Go ahead and create a PR.

**Comment by meetcric** [comment]
i wanna do this

**Comment by arshadkazmi42** [comment]
@meetcric I think @msarfrazanwar is working on this. You can check other issues, and I will be adding some more good first issues tomorrow. Also you can check my other repos which has some issues
