### ISSUE TITLE
Comment out all Output in README

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#116]
1. Comment out all the outputs in the README file usage examples.
2. Add a link break before the `Output` statements.

**Comment by albanmahmut** [comment]
Can I contribute?

**Comment by arshadkazmi42** [comment]
@albanmahmut Yes. Go ahead. Create a PR.

**Comment by albanmahmut** [comment]
> @albanmahmut Yes. Go ahead. Create a PR.

This was my first contribution, hope all is done good.
