### ISSUE TITLE
Update gitignore

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#17]
Update gitignore file to ignore IDE config files

**Comment by arshadkazmi42** [comment]
@hiteshpr you can take this

**Comment by shubhankarb180** [comment]
Can i get to know more about updating this ignore IDE config files ... where are they in repo ? #17

**Comment by arshadkazmi42** [comment]
@shubhankarb180 @hiteshpr will be working on this.
As he was about to work on the issue to create gitignore which you did, so I have given this to @hiteshpr
If @hiteshpr does not replies in a day or two then you can take this up.

**Comment by shubhankarb180** [comment]
No Issue ... I can wait ... @arshadkazmi42

**Comment by rajatjain-21** [comment]
Hey @arshadkazmi42 , won't this be ide specific?

**Comment by arshadkazmi42** [comment]
@rajatjain-21 yes it is and we would want to have atleast for some popuplar IDE's like Webstorm, VSCode, atom....

**Comment by tonystark97** [comment]
@arshadkazmi42 If you allow, can I add package.json to .gitignore?

**Comment by shubhankarb180** [comment]
Is someone working on this issue ?

**Comment by arshadkazmi42** [comment]
@shubhankarb180 I don't think anyone is working on this, you can take this up

**Comment by Apoorva-13** [comment]
can I take  this up?

**Comment by arshadkazmi42** [comment]
@Apoorva-13 yes. go ahead.

**Comment by Apoorva-13** [comment]
Sorry but i can't figure out what other ide config file needs to be ignored as already node modules is there in gitignore. pls correct me if i am wrong

**Comment by arshadkazmi42** [comment]
https://www.gitignore.io/

you can try this

**Comment by Apoorva-13** [comment]
Thanks:)

# Created by https://www.gitignore.io/api/node

### Node ###
# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc test coverage
.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1 declaration files
typings/

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variables file
.env

# parcel-bundler cache (https://parceljs.org/)
.cache

# next.js build output
.next

# nuxt.js build output
.nuxt

# vuepress build output
.vuepress/dist

# Serverless directories
.serverless


# End of https://www.gitignore.io/api/node






Should I add all this to gitignore?

**Comment by arshadkazmi42** [comment]
yes. you can add all these

**Comment by Apoorva-13** [comment]
Thanks:)
