### ISSUE TITLE
Add CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#3]
We need code_of_conduct exactly like this

https://raw.githubusercontent.com/arshadkazmi42/simple-date-validator/master/CODE_OF_CONDUCT.md

with the same file name also.

**Comment by msarfrazanwar** [comment]
I want to do this.

**Comment by arshadkazmi42** [comment]
Cool. Go ahead 👍
