### ISSUE TITLE
Add gitignore file

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#4]
Add gitignore file for the node project

**Comment by hiteshpr** [comment]
Hi, can I work on this issue?

**Comment by arshadkazmi42** [comment]
@hiteshpr Yes. Its yours. Go ahead and create a PR 👍

**Comment by arshadkazmi42** [comment]
@hiteshpr Are you working on this? I forgot you have take this. But @shubhankarb180 has already added this, I have created on more issue to update gitignore to ignore ide config files something like this here #17. you can work on that.

something like this
https://github.com/arshadkazmi42/ak-logger/blob/master/.gitignore
