### ISSUE TITLE
Add Codacy Badge in README

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#59]
**Describe the bug**
Add code quality badge to readme

**Additional context**
Add Code Quality badge next to downloads badge in README file

just copy the below code and add it in readme below downloads code 

`[![Codacy Badge](https://api.codacy.com/project/badge/Grade/a47235834dff4a88ae37bdc7460a5c7d)](https://www.codacy.com/app/arshadkazmi42/custom-date-formatting?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=arshadkazmi42/custom-date-formatting&amp;utm_campaign=Badge_Grade)`

**To work on this**
1. Put a comment here who ever is working on it.
2. Also tag this issue in your Pull Request description.

**Note:** Anyone who is not following above two steps, their PR will be rejected

**Comment by BK1603** [comment]
Can I do this?
:smile:

**Comment by arshadkazmi42** [comment]
@BK1603 Its first timers only, if you have not contributed to this repo, then go ahead and create a PR

**Comment by BK1603** [comment]
Well then this shall be my first one here!
Thanks a lot for the quick response :smile:

**Comment by arshadkazmi42** [comment]
@BK1603 I was thinking let's keep it for new contributors who are starting with opensource.
You can take some other issue. I will be adding some more issues here.

**Comment by BK1603** [comment]
Oh yeah Its cool! :smile: I will be watching here then!

**Comment by mensonones** [comment]
I requested PR

**Comment by arshadkazmi42** [comment]
> I requested PR

We are keeping it for new contributors.

**Comment by Kvaibhav01** [comment]
I've just started working on this.

**Comment by mensonones** [comment]
I understand. good luck

**Comment by arshadkazmi42** [comment]
@Kvaibhav01 Its first-timers-only. Only work on this if this is your first contribution

**Comment by Kvaibhav01** [comment]
@arshadkazmi42 I'm a first-timer for this repo. What do you mean by _first-timers_?

**Comment by arshadkazmi42** [comment]
> @arshadkazmi42 I'm a first-timer for this repo. What do you mean by _first-timers_?

Who have just started with Open source and its their first PR.

**Comment by alvintan05** [comment]
Can I work on this ?

**Comment by arshadkazmi42** [comment]
@alvintan05 Yes. Go ahead create a PR
