### ISSUE TITLE
Test Script cleanup

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#6]
Uncomment the code here,

https://github.com/arshadkazmi42/custom-date-formatting/blob/master/test/index.js#L16-L26

and change hard coded datetime values to generate dynamically using moment

**Comment by mathiasdonoso** [comment]
I made this pr for this issue https://github.com/arshadkazmi42/custom-date-formatting/pull/36

**Comment by mathiasdonoso** [comment]
> I made this pr for this issue #36

Oops, I didn't figure out that @iagocavalcante already fix it, my bad.

**Comment by arshadkazmi42** [comment]
@rogers9798 is working on this, so please do not create any other PR for this issue.

**Comment by arshadkazmi42** [comment]
@rogers9798 Thank you for working on this.

**Comment by rogers9798** [comment]
@arshadkazmi42  It was awesome working with you
