### ISSUE TITLE
Fix Contributors Link

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#62]
All the contributors name added here are in wrong format
https://github.com/arshadkazmi42/custom-date-formatting/blob/master/Contributors.md

it needs to be something like this
`[Arshad Kazmi](https://github.com/arshadkazmi42)`

So for this, `[]` these brackets needs to be added in all names.

**Steps to work on this**
1. Comment Here that you are working on it. 
2. Create PR. (No need to wait for anyone's reply)
3. Add this in your PR description `Closes #62` (This is not your commit message)

**Important Note**

First person to comment here, gets the issue.
Is someone is working on it, please do no create duplicate request.
Check with the person who has commented first whether they are continuing with it or not.
If they are not continuing, then you can add comment here and create a new PR.

**Note:** Work on a feature branch, do not work on master branch.

**Comment by marimendes** [comment]
Please check https://github.com/arshadkazmi42/custom-date-formatting/pull/63 :v:
