### ISSUE TITLE
Change getNextOrPrevDateCustomFormat in readme

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#67]
It needs to change as below

`getNextOrPrevDateCustomFormat => Custom Format date with days (+/-)`

in the README.md file

**Comment by harshalitalele** [comment]
Do you want the same format for all the time, seconds, etc titles?
You just want to change the content format right?

**Comment by arshadkazmi42** [comment]
I have added separate issues for each title, so for new contributors, it will be easy to get started.
you can work on any one which ever you are interested in

**Comment by harshalitalele** [comment]
I am not the first timer actually.
Just came across this and tried to see if I can solve.
I wouldn't do this then and I think we should delete these comments as it would be confusing for the first timers.

**Comment by locke189** [comment]
Im on it

**Comment by alvintan05** [comment]
I want to work on this
