### ISSUE TITLE
Change customSourceDateFormatToCustomNewDateFormat in readme

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#70]
It needs to change as below

`customSourceDateFormatToCustomNewDateFormat => Custom Source Format date custom new format`

in the README.md file

**Comment by devkant** [comment]
Can i claim this?

**Comment by arshadkazmi42** [comment]
@devkant yes. go ahead

**Comment by arshadkazmi42** [comment]
@devkant you have created this PR in your forked repo. Can you create this PR in this repo
