### ISSUE TITLE
Comment formatting

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#72]
Add space after `//` in the comments, in the usage sample which is present in readme

`//This will return a string with new date`
change to
`// This will return a string with new date`

Change this for all the usage samples

**Comment by shrey183** [comment]
Hi, I can do this. Please assign.

**Comment by arshadkazmi42** [comment]
go for it 👍

**Comment by shrey183** [comment]
I have created a Pull request. Is it alright?
