### ISSUE TITLE
Add output of getTimeStampFromCurrentDateFormat

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#77]
Add output of the usage in readme file here

https://github.com/arshadkazmi42/custom-date-formatting#gettimestampfromcurrentdateformat

Add this output

`Output: 1503858600000`

**Comment by Apoorva-13** [comment]
I would like to work on this.

**Comment by arshadkazmi42** [comment]
Cool. Go ahead

**Comment by Apoorva-13** [comment]
where exactly i have to place this output? and what should be the format?

**Comment by arshadkazmi42** [comment]
@Apoorva-13 add it here

<img width="954" alt="screen shot 2018-10-06 at 1 08 53 am" src="https://user-images.githubusercontent.com/4654382/46556489-7385c980-c904-11e8-9562-8d614d8ce2d0.png">

Below the last line

**Comment by Apoorva-13** [comment]
ok sure thanks:)

**Comment by arshadkazmi42** [comment]
You have created a new PR for gitignore, but you have not updated your existing PR.
https://github.com/arshadkazmi42/custom-date-formatting/pull/85/files

Should I close this PR? As gitignore changes are there in this PR also.

**Comment by alvintan05** [comment]
Can I work on this ?

**Comment by arshadkazmi42** [comment]
@Apoorva-13 was already working on it. If they are not doing it, you can take this up.

**Comment by alvintan05** [comment]
Okay, I will take the other issue

**Comment by arshadkazmi42** [comment]
@alvintan05 There has been no update from @Apoorva-13 , you can work on it if you want

**Comment by Apoorva-13** [comment]
Sorry Was I supposed make some other changes as well? felt I had done the needful.

**Comment by arshadkazmi42** [comment]
@Apoorva-13 No issues. I have merge @alvintan05 's PR. You can work on other open issues

**Comment by Apoorva-13** [comment]
Ok, But atleast let me know what had I missed?
