### ISSUE TITLE
Create Contributors.md file

### ISSUE THREAD

**Issue by arshadkazmi42** [arshadkazmi42/custom-date-formatting#9]
Create a Contributors.md file in root directory which will contain list of contributors in this syntax

```
# Contributors

- [Arshad Kazmi](https://github.com/arshadkazmi42)
```

Also do add yourself to the list

**Comment by mynkdhmn** [comment]
May I take this issue?

**Comment by arshadkazmi42** [comment]
@mynkdhmn its yours. Go ahead and create a PR

**Comment by mynkdhmn** [comment]
Sure. Done with it. Any improvements?

**Comment by arshadkazmi42** [comment]
@mynkdhmn Thank you for working on this.
I have suggested some changes in your PR. You can have a look here #11
